import Head from 'next/head'
import styles from '../styles/Home.module.css'
import styled from "@emotion/styled";


const Home = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Examen B1</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="https://th.bing.com/th/id/R.eea5e4678b232837975a2ae8c3140fa5?rik=2Ym%2foqBJKKLwQg&pid=ImgRaw&r=0&sres=1&sresct=1"/>
            </Head>
            <main className={styles.main}>
                <h1 className={styles.title}>
                    Bienvenido a App
                </h1>

                <a href={"/elegidos"}>
                    Ingresar
                </a>
            </main>
        </div>
    )
}

export default Home